export const COORDINATES_CLICKED = "COORDINATES_CLICKED";
export const COUNTRY_FETCHED = "COUNTRY_FETCHED";
export const COUNTRY_NOT_FETCHED = "COUNTRY_NOT_FETCHED";
export const MOVIE_FETCHED = "MOVIE_FETCHED";
