export const COORDINATES_FETCHED = "COORDINATES_FETCHED";
export const COUNTRY_CODE_FETCHED = "COUNTRY_CODE_FETCHED";
export const COUNTRY_CODE_NOT_FETCHED = "COUNTRY_CODE_NOT_FETCHED";
export const COUNTRY_FETCHED = "COUNTRY_FETCHED";
export const MOVIE_TITLES_FETCHED = "MOVIE_TITLES_FETCHED";
export const MOVIE_DATA_FETCHED = "MOVIE_FETCHED";
